blank_issues_enabled: false
contact_links:
  - name: Security Contact
    about: Please report security vulnerabilities to security@tiangolo.com
  - name: Discussion
    about: Please ask and answer questions in discussions.
    url: https://github.com/tiangolo/github-actions-sandbox/discussions
