name: Question or Problem
description: Ask a question or ask about a problem
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in FastAPI! 🚀

        Please follow these instructions, fill every question, and do every step. 🙏
        
        I'm asking this because answering questions and solving problems in GitHub issues is what consumes most of the time.
        
        I end up not being able to add new features, fix bugs, review Pull Requests, etc. as fast as I wish because I have to spend too much time handling issues.

        All that, on top of all the incredible help provided by a bunch of community members that give a lot of their time to come here and help others.

        That's a lot of work they are doing, but if more FastAPI users came to help others like them just a little bit more, it would be much less effort for them (and you and me 😅).

        By asking questions in a structured way (following this) it will be much easier to help you.
        
        And there's a high chance that you will find the solution along the way and you won't have to even submit it and wait for an answer. 😎

        As there are too many issues with questions, I'll have to close the incomplete ones. That will allow me (and others) to focus on helping people like you that follow the whole process and help us help you. 🤓
  - type: checkboxes
    id: checks
    attributes:
      label: First check
      description: Please check all the following
      options:
        - label: I added a very descriptive title to this issue.
          required: true
        - label: I used the GitHub search to find a similar issue and didn't find it.
          required: true
        - label: I searched the FastAPI documentation, with the integrated search.
          required: true
        - label: I already searched in Google "How to X in FastAPI" and didn't find any information.
          required: true
        - label: I already read and followed all the tutorial in the docs and didn't find an answer.
          required: true
        - label: I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
          required: true
        - label: I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
          required: true
        - label: I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
          required: true
        - label: |
            After submitting this, I commit to one of:
            * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
            * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
            * Implement a Pull Request for a confirmed bug.
  - type: markdown
    attributes:
      value: |
        All of the above items must be checked. 🙏👆
  - type: textarea
    id: example
    attributes:
      label: Example code
      description: |
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with your use case.

      placeholder: "self-contained, minimal, reproducible, example that can be copied and pasted, and then run"
      value: |
        ```Python
        # Replace the code below with your own self-contained, minimal, reproducible, example.
        # If I (or someone) can copy it, run it, and see it right away, there's a much higher chance I (or someone) will be able to help you.
        from fastapi import FastAPI

        app = FastAPI()


        @app.get("/")
        def read_root():
            return {"Hello": "World"}
        ```
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: description
      description: What is the problem, question, or error?
      placeholder: A short description telling me what you are doing, what you expect to happen, and what is currently happening.
      value: |
        * Open the browser and call the endpoint `/`.
        * It returns a JSON with `{"Hello": "World"}`.
        * But I expected it to return `{"Hello": "Sara"}`.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you on?
      multiple: true
      options:
        - Linux
        - Windows
        - macOS
        - Other
    validations:
      required: true
  - type: textarea
    id: os-details
    attributes:
      label: Operating System Details
      description: You can add more details about your operating system here, in particular if you chose "Other".
  - type: input
    id: fastapi-version
    attributes:
      label: FastAPI version
      description: |
        What FastAPI version are you using?

        You can find out with:

        ```bash
        python -c "import fastapi; print(fastapi.__version__)"
        ```
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: What Python version are you using?
      description: |
        You can find the Python version with:

        ```bash
        python --version
        ```
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any additional context information or screenshots you think are useful.
