name: Deploy Docs
on:
  workflow_run:
    workflows:
      - Build Docs
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Download Artifact Docs
        uses: dawidd6/action-download-artifact@v2.9.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          # Required, workflow file name or ID
          workflow: build-docs.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: docs-zip
      # - name: Secure tmate session
      #   run: curl https://github.com/tiangolo.keys > ~/.tmate_authorized_keys && echo 'set tmate-authorized-keys "~/.tmate_authorized_keys"' > ~/.tmate.conf
      # - name: Debug tmate
      #   run: cat ~/.tmate_authorized_keys && echo "authorized_keys" && cat ~/.tmate.conf
      - name: Comment Deploy
        # Only run on PR workflows
        if: github.event.workflow_run.pull_requests[0].number > 0
        env:
          PR: "${{ github.event.workflow_run.pull_requests[0].number }}"
          DEPLOY_URL: "nope"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          COMMIT: "${{ github.event.workflow_run.pull_requests[0].head.sha }}"
        run: bash ./docs-comment-deploy.sh
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
