name: Issue Manager

on:
  schedule:
    - cron: "* * * * *"
  issue_comment:
    types:
      - created
  issues:
    types:
      - labeled
  pull_request_target:
    types:
      - labeled
  workflow_dispatch:

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: tiangolo/issue-manager@only-labels
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: '{"answered": {"delay": 300}, "complete": {"delay": 300, "message": "Completed!"}}'
