name: Latest Changes

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: 'false'

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # To allow latest-changes to commit to the main branch
        token: ${{ secrets.SANDBOX_TOKEN }}
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    # Allow debugging with tmate
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true' }}
      with:
        limit-access-to-actor: true
    - uses: docker://ghcr.io/tiangolo/latest-changes:latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        latest_changes_file: docs/en/docs/release-notes.md
        latest_changes_header: '# Release Notes\n\n'
        template_file: ./.github/workflows/release-notes.jinja2
        debug_logs: true
